---
## Title: deploy.yml
## Description: Deploy Docker Swarm Services
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-09-15 09:37:44
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# - name: Setup Mount Points
#   hosts: all
#   gather_facts: true
#   user: ubuntu
#   become: true
#   tasks:
#     - name: Ensure nfs-common is installed
#       ansible.builtin.apt:
#         name: nfs-common
#         state: present
#         update_cache: true
#       tags:
#         - nfs
#         - setup

#     - name: Create mount point directory
#       ansible.builtin.file:
#         path: "{{ mount_point }}"
#         state: directory
#         owner: ubuntu
#         group: ubuntu
#         mode: '0755'
#       loop:
#         - /docker/
#         - /mnt/nvme
#         - /mnt/nvme/docker_storage
#         - /mnt/nfs/bt/Storage
#         - /mnt/nfs/backup
#         - /mnt/nfs/storage
#         - /mnt/nfs/torrents
#       loop_control:
#         loop_var: mount_point
#       tags:
#         - nfs
#         - setup

    # https://evodify.com/change-docker-storage-location/
    

    # AI just did all of this, and I do not like it, but it works. So be it.
    # - name: Configure Docker to use new storage location
    #   ansible.builtin.copy:
    #     dest: /etc/docker/daemon.json
    #     content: |
    #       {
    #           "data-root": "/mnt/nvme/docker_storage"
    #       }
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   notify:
    #     - Restart Docker
    #   tags:
    #     - docker
    #     - setup

    # - name: Mount NFS Shares
    #   ansible.builtin.mount:
    #     path: "{{ nfs_mount_point.path }}"
    #     src: "{{ nfs_mount_point.src }}"
    #     fstype: nfs
    #     opts: x-systemd.after=network-online.target,x-systemd.automount,nofail,noauto,rw
    #     state: mounted
    #   loop:
    #     - src: 10.1.1.7:/mnt/Dedicated/Storage/
    #       path: /mnt/nfs/bt/Storage
    #     - src: rk1-cluster03:/mnt/storage
    #       path: /mnt/nfs/storage
    #     - src: rk1-cluster03:/mnt/torrents
    #       path: /mnt/nfs/torrents
    #     - src: rk1-cluster03:/mnt/backup
    #       path: /mnt/nfs/backup
    #     - src: blacktower:/mnt/backup
    #       path: /mnt/nfs/backup
    #   loop_control:
    #     loop_var: nfs_mount_point
    #   tags:
    #     - nfs
    #     - setup



- name: Add labels to nodes
  hosts: all
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Remove all labels assigned to node
      community.docker.docker_node:
        hostname: "{{ inventory_hostname }}"
        labels_state: replace
      tags:
        - docker
        - setup
        - remove_labels

    - name: Add mylabel to Cluster
      community.docker.docker_node:
        hostname: "{{ label.node }}"
        labels: "{{ label.name }}={{label.value | default('true') }}"
        labels_state: merge
      loop:
        - node: rk1-cluster03
          name: storage
          value: true
        - node: rk1-cluster01
          name: bigmem
          value: true
        - node: rk1-cluster01
          name: rk1
          value: true
        - node: rk1-cluster02
          name: rk1
          value: true
        - node: rk1-cluster03
          name: rk1
          value: true
        - node: rk1-cluster04
          name: rk1
          value: true
      loop_control:
        loop_var: label
      tags:
        - docker
        - setup
        - add_labels


- name: Deploy Docker Swarm Services
  hosts: rk1-main
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Setup janitor
      ansible.builtin.include_tasks: tasks/janitor.yml
      tags: [janitor]

    - name: Setup Traffic
      ansible.builtin.include_tasks: tasks/traefik3.yml
      tags: [traefik, whoami]

    - name: Setup portainer
      ansible.builtin.include_tasks: tasks/portainer.yml
      tags: [portainer]

    - name: Setup pihole
      tags: [pihole]
      ansible.builtin.include_tasks: tasks/pihole.yml

    - name: Setup Change Detection
      ansible.builtin.include_tasks: tasks/changedetection.yml
      tags: [changedetection]

    - name: Setup Wolnut
      ansible.builtin.include_tasks: tasks/wolnut.yml
      tags: [wolnut]

    - name: Setup Grafana
      ansible.builtin.include_tasks: tasks/grafana.yml
      tags: [grafana]

    - name: Setup Prometheus
      ansible.builtin.include_tasks: tasks/prometheus.yml
      tags: [prometheus]

    - name: Setup ROMM
      ansible.builtin.include_tasks: tasks/romm.yml
      tags: [romm]

    - name: Setup Smokeping
      ansible.builtin.include_tasks: tasks/smokeping.yml
      tags: [smokeping]

    - name: Setup Homepage
      ansible.builtin.include_tasks: tasks/homepage.yml
      tags: [homepage]

    - name: Setup n8n
      ansible.builtin.include_tasks: tasks/n8n.yml
      tags: [n8n]

    - name: Setup paperless-ngx
      ansible.builtin.include_tasks: tasks/paperless-ngx.yml
      tags: [paperless_ngx,paperless,paperless_web,paperless_db]

    - name: Remove ARR from cluster
      ansible.builtin.include_tasks: tasks/arr/no-arr.yml
      tags: [no_arr]

    - name: Add telegraf user to Docker Group
      ansible.builtin.user:
        name: telegraf
        groups: docker
        append: true
      notify:
        - Restart telegraf

      tags: [telegraf]
    - name: Add ubuntu user to Docker Group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true
  roles:
    - role: setup
      tags: [setup, packages]
    - role: geerlingguy.pip
      tags: [python, pip]
  vars_files:
    - main.yml
    - main.vault.yml
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    docker_network: the_ways
    traefik_proxy_network: traefik_proxy


### These are in development

    # - name: Setup Homepage
    #   ansible.builtin.include_tasks: tasks/stacks/homepage.yml
    #   tags: [homepage-stack]