---
## Title: deploy.yml
## Description: Deploy Docker Swarm Services
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-09-15 09:37:44
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

- name: Deploy Docker Swarm Services
  hosts: rk1_main
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Setup janitor
      ansible.builtin.include_tasks: tasks/janitor.yml
      tags: [janitor]
    - name: Setup Traffic
      ansible.builtin.include_tasks: tasks/traefik3.yml
      vars:
        traefik_selfsign: false
      tags: [traefik, whoami]
    - name: Setup portainer
      ansible.builtin.include_tasks: tasks/portainer.yml
      tags: [portainer]

    - name: Setup pihole
      tags: [pihole]
      ansible.builtin.include_tasks: tasks/pihole.yml
    # - name: Setup apt-cacher-ng
    #   ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
    #   tags: [apt-cacher-ng]
    - name: Setup Discount Bandit
      ansible.builtin.include_tasks: tasks/discount-bandit.yml
      tags: [discount-bandit]
    - name: Setup Change Detection
      ansible.builtin.include_tasks: tasks/changedetection.yml
      tags: [changedetection]
    - name: Setup Wolnut
      ansible.builtin.include_tasks: tasks/wolnut.yml
      tags: [wolnut]
    - name: Setup Grafana
      ansible.builtin.include_tasks: tasks/grafana.yml
      tags: [grafana]

    # - name: Setup ROMM
    #   ansible.builtin.include_tasks: tasks/romm.yml
    #   tags: [romm]

    - name: Setup Smokeping
      ansible.builtin.include_tasks: tasks/smokeping.yml
      tags: [smokeping]

    - name: Setup Smokeping2
      ansible.builtin.include_tasks: tasks/smokeping2.yml
      tags: [smokeping2]

    - name: Setup Homepage
      ansible.builtin.include_tasks: tasks/homepage.yml
      tags: [homepage]

    - name: Setup Homepage
      ansible.builtin.include_tasks: tasks/stacks/homepage.yml
      tags: [homepage-stack]

    - name: Setup n8n
      ansible.builtin.include_tasks: tasks/n8n.yml
      tags: [n8n]
    # Deploy ARR Services {Deluge}
    # - name: Setup deluge
    #   ansible.builtin.include_tasks: tasks/arr/deluge.yml
    #   tags: [deluge]
    - name: Setup Arr Stack
      ansible.builtin.include_tasks: tasks/arr/arr.yml
      tags: [arr]

    - name: Add telegraf user to Docker Group
      ansible.builtin.user:
        name: telegraf
        groups: docker
        append: true
      notify:
        - Restart telegraf

      tags: [telegraf]
    - name: Add ubuntu user to Docker Group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true
  roles:
    - role: setup
      tags: [setup, packages]
    - role: geerlingguy.pip
      tags: [python, pip]
  vars_files:
    - main.yml
    - main.vault.yml
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    docker_network: the_ways
    traefik_proxy_network: traefik_proxy