---
# File: deploy.yml

- name: Deploy Docker Swarm Services
  hosts: rk1_main
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Setup janitor
      ansible.builtin.include_tasks: tasks/janitor.yml
    - name: Setup Traffic
      ansible.builtin.include_tasks: tasks/traefik.yml
      vars:
        traefik_selfsign: false
    - name: Setup portainer
      ansible.builtin.include_tasks: tasks/portainer.yml
    # - name: Setup apt-cacher
    #   ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
    - name: Setup pihole
      ansible.builtin.include_tasks: tasks/pihole.yml
    - name: Setup apt-cacher-ng
      ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
    # - name: Setup 'isp-pollution'
    #   ansible.builtin.include_tasks: tasks/isp-pollution.yml
    - name: Setup Discount Bandit
      ansible.builtin.include_tasks: tasks/discount-bandit.yml
      tags: [discount-bandit]
    - name: Setup Change Detection
      ansible.builtin.include_tasks: tasks/changedetection.yml
      tags: [changedetection]
    - name: Setup Wolnut
      ansible.builtin.include_tasks: tasks/wolnut.yml
      tags: [wolnut]
    - name: Setup ROMM
      ansible.builtin.include_tasks: tasks/romm.yml
      tags: [romm]

# Run basic hosts setup
    - name: Add telegraf user to Docker Group
      ansible.builtin.user:
        name: telegraf
        groups: docker
        append: true
      notify:
        - Restart telegraf

  roles:
    - role: geerlingguy.pip
      tags: [python, pip]
    # - role: swarm-smokeping
    #   tags: [ smokeping ]
  #   - role: apt-prep
  #     vars:
  #       apt_proxy_path: http://apt-cacher-ng.mcharryville.space:3142/
  #     tags: apt, ubuntu
  #   - role: gluster-docker
  #     tags: gluster, docker
    # - role: geerlingguy.docker
    #   vars:
    #     docker_users:
    #     - ubuntu
    #   tags: docker

  vars_files:
    - main.yml
    - main.vault.yml

