---
## Title: deploy.yml
## Description: Deploy Docker Swarm Services
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-09-15 09:37:44
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

- name: Deploy Docker Swarm Services
  hosts: rk1_main
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Setup janitor
      ansible.builtin.include_tasks: tasks/janitor.yml
    - name: Setup Traffic
      ansible.builtin.include_tasks: tasks/traefik.yml
      vars:
        traefik_selfsign: false
      tags: [traefik, whoami]
    - name: Setup portainer
      ansible.builtin.include_tasks: tasks/portainer.yml
    - name: Setup pihole
      tags: [pihole]
      ansible.builtin.include_tasks: tasks/pihole.yml
    - name: Setup apt-cacher-ng
      ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
      tags: [apt-cacher-ng]
    - name: Setup Discount Bandit
      ansible.builtin.include_tasks: tasks/discount-bandit.yml
      tags: [discount-bandit]
    - name: Setup Change Detection
      ansible.builtin.include_tasks: tasks/changedetection.yml
      tags: [changedetection]
    - name: Setup Wolnut
      ansible.builtin.include_tasks: tasks/wolnut.yml
      tags: [wolnut]
    # - name: Setup ROMM
    #   ansible.builtin.include_tasks: tasks/romm.yml
    #   tags: [romm]
    - name: Setup Smokeping
      ansible.builtin.include_tasks: tasks/smokeping.yml
      tags: [smokeping]
    - name: Setup Homepage
      ansible.builtin.include_tasks: tasks/homepage.yml
      tags: [homepage]
    - name: Setup n8n
      ansible.builtin.include_tasks: tasks/n8n.yml
      tags: [n8n]
    - name: Add telegraf user to Docker Group
      ansible.builtin.user:
        name: telegraf
        groups: docker
        append: true
      notify:
        - Restart telegraf
      tags: [telegraf]
  roles:
    - role: geerlingguy.pip
      tags: [python, pip]
  vars_files:
    - main.yml
    - main.vault.yml
