---
- hosts: rk1_main
  gather_facts: no
  user: ubuntu
  become: true
  vars_files:
    - main.vault.yml
    - main.yml
  tasks:
    - name: Setup janitor
      ansible.builtin.include_tasks: tasks/janitor.yml
    - name: Setup Traffic
      ansible.builtin.include_tasks: tasks/traefik.yml
      vars:
        traefik_selfsign: false
    # - name: Setup portainer
    #   ansible.builtin.include_tasks: tasks/portainer.yml
    # - name: Setup apt-cacher
    #   ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
    # - name: Setup pihole
    #   ansible.builtin.include_tasks: tasks/pihole.yml
    # - name: Setup apt-cacher-ng
    #   ansible.builtin.include_tasks: tasks/apt-cacher-ng.yml
    # - name: Setup 'isp-pollution'
    #   ansible.builtin.include_tasks: tasks/isp-pollution.yml
    # - name: Setup Discount Bandit
    #   ansible.builtin.include_tasks: tasks/discount-bandit.yml
    # - name: Setup Change Detection
    #   ansible.builtin.include_tasks: tasks/changedetection.yml
    # - name: Add telegraf user to Docker Group
    #   ansible.builtin.user:
    #     name: telegraf
    #     groups: docker
    #     append: true
    # - name: Restart telegraf
    #   ansible.builtin.service:
    #     name: telegraf
    #     state: restarted

  roles:
    # - role: swarm-smokeping
    #   tags: [ smokeping ]
  #   - role: apt-prep
  #     vars:
  #       apt_proxy_path: http://apt-cacher-ng.mcharryville.space:3142/
  #     tags: apt, ubuntu
  #   - role: gluster-docker
  #     tags: gluster, docker
    # - role: geerlingguy.docker
    #   vars:
    #     docker_users:
    #     - ubuntu
    #   tags: docker
    # - role: geerlingguy.pip
    #   tags: python, pip