---
- name: Ansible RK1 Cluster Setup
  hosts: all
  gather_facts: true
  user: ubuntu
  become: true
  pre_tasks:
    # - name: Fix systemd resolved
    #   ansible.builtin.copy:
    #     src: resolved.conf
    #     dest: /etc/systemd/resolved.conf
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: '0644'
    #   notify: restart resolved

    # - name: Create symlink for systemd resolved
    #   ansible.builtin.file:
    #     src: /run/systemd/resolve/resolv.conf
    #     dest: /etc/resolv.conf
    #     state: link

    # - name: Install NFS server
    #   ansible.builtin.apt:
    #     name: nfs-kernel-server
    #     state: present
    #     update_cache: yes
    #   when: inventory_hostname == "rk1-cluster03.mcharryville.space"

    # - name: Install NFS client
    #   ansible.builtin.apt:
    #     name: nfs-common
    #     state: present
    #     update_cache: no

    - name: Mount NFS partitions
      ansible.posix.mount:
        src: "rk1-cluster03:/mnt/{{ nfs_directory }}"
        path: "/mnt/nfs/{{ nfs_directory }}"
        opts: "x-systemd.automount,nofail"
        boot: false
        state: unmounted
        fstype: nfs
      with_items: 
      - storage
      - torrents
      - backup
      loop_control:
        loop_var: 'nfs_directory'

    - name: 'Create directory for NFS'
      ansible.builtin.file:
        path: "/mnt/nfs/{{ dir }}"
        owner: '1000'
        group: '1001'
        mode: '0775'
        state: 'directory'
      loop:
        - 'backup'
        - 'storage'
        - 'torrents'
      loop_control:
        loop_var: 'dir'

    - name: Mount NFS partitions
      ansible.posix.mount:
        src: "rk1-cluster03:/mnt/{{ nfs_directory }}"
        path: "/mnt/nfs/{{ nfs_directory }}"
        opts: "soft,nofail"
        boot: true
        state: mounted
        fstype: nfs
      with_items: 
      - storage
      - torrents
      - backup
      loop_control:
        loop_var: 'nfs_directory'
  roles:
    - role: geerlingguy.pip
      tags: [python, pip]
    - role: geerlingguy.docker
      tags: [docker, install]
    # - role: update
    #   vars:
    #     update_apt_proxy_path: http://apt-cacher-ng.mcharryville.space:3142/
    #   throttle: 1
    #   tags: [apt, ubuntu]
    # - role: docker-swarm
    #   tags: [docker, swarm, docker-swarm]
    # - role: keepalive
    #   tags: keepalive
    #   vars:
    #     keepalive_ip:
    #       - 10.1.1.35
  vars_files:
    - main.vault.yml
    - main.yml
