---
- name: Ansible RK1 Cluster Setup
  hosts: all
  gather_facts: true
  user: ubuntu
  become: true
  tasks:
    - name: Fix systemd resolved
      ansible.builtin.copy:
        src: resolved.conf
        dest: /etc/systemd/resolved.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      notify: reboot systemd

    - name: Create symlink for systemd resolved
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link


  roles:
    - role: geerlingguy.pip
      tags: [python, pip]
    - role: update
      vars:
        update_apt_proxy_path: http://apt-cacher-ng.mcharryville.space:3142/
      tags: [apt, ubuntu]
    - role: keepalive
      tags: keepalive
      vars:
        keepalive_ip:
          - 10.1.1.35
  vars_files:
    - main.vault.yml
    - main.yml
