---

## Title: mining.yml
## Description: Start/Stop Mining Service
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-09-15 09:38:02
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

- hosts: all
  gather_facts: no
  user: ubuntu
  become: true
  tasks:
    - name: Start Mining tasks
      ansible.builtin.systemd_service:
        name: miner.service
        state: started
        enabled: true
      tags:
        - "start_mining"
    - name: Stop Mining tasks
      ansible.builtin.systemd_service:
        name: miner.service
        state: stopped
        enabled: false
      tags:
        - "stop_mining"