---
# -------------------------------------------
# Configure NGINX Proxy Manager
#
# Required:
#   guest_name - name of guest running NPM
#   app_name - app name to proxy
#   proxy.port - port to proxy to
# Optional:
#   proxy.name - hostname to proxy (default app_name)
#   proxy.host - hostname to proxy to (default guest_name)
#   proxy.protocol - protocol to proxy (default http)
# -------------------------------------------

- name: Configure NGINX Proxy Manager
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Get Proxy Authentication Token
    uri:
      url: "http://{{ guest_name }}:81/api/tokens"
      method: POST
      body:
        identity: "admin@example.com"
        secret: changeme
      body_format: json
    register: login_results

  - name: Configure Proxy Host for "{{ app_name }}"
    uri:
      url: "http://{{ guest_name }}:81/api/nginx/proxy-hosts"
      method: POST
      status_code: 201
      headers:
        Authorization: "Bearer {{ login_results.json.token }}"
      body_format: json
      body:
        domain_names:
        - "{{ proxy['name'] | default(app_name) }}"
        forward_scheme: "{{ proxy['protocol'] | default('http') }}"
        forward_host: "{{ proxy['host'] | default(guest_name) }}"
        forward_port: "{{ proxy['port'] | int }}"
        allow_websocket_upgrade: true
        # block_exploits: false
        # access_list_id: 0
        # certificate_id: 0
        # meta:
        #   letsencrypt_agree: false
        #   dns_challenge: false
        # advanced_config: ""
        # locations: []
        # caching_enabled: false
        # http2_support: false
        # hsts_enabled: false
        # hsts_subdomains: false
        # ssl_forced: false
    register: response
    changed_when: response.status == 201
    when: proxy_state | default('present') != 'absent'