---
- hosts: all
  gather_facts: no
  user: ubuntu
  become: true
  tasks:
    - name: Stop Mining tasks
      ansible.builtin.systemd_service:
        name: miner.service
        state: stopped
        enabled: false
