---
- hosts: rk1_main
  gather_facts: no
  user: ubuntu
  become: true
  tasks:
    - name: 'Deploy pollution Generator'
      community.docker.docker_swarm_service:
        name: 'isp-pollution'
        # image: "hvalev/isp-pollution"
        image: "mq83/noisy"
        force_update: true
        env:
        networks:
          - 'traefik_backend'
        mode: 'replicated'
        replicas: 0
        restart_config:
          condition: "{{ restart_condition }}"
        # placement:
        #   constraints:
        #     - 'node.role == worker'
      no_log: "{{ not docker_service_debug }}"