---
- name: 'Create network'
  community.docker.docker_network:
    name: 'discountbandit_backend'
    driver: 'overlay'
  tags:
    - discountbandit

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: 'root'
    group: 'root'
    mode: '0775'
    state: 'directory'
  loop:
    - 'discountbandit-config'
    - 'discountbandit-data'
    - 'discountbandit-data/vendor'
  loop_control:
    loop_var: 'dir'

- name: 'Remove discountbandit'
  community.docker.docker_swarm_service:
    name: 'discountbandit'
    state: absent
    replicas: 0

- name: 'Deploy discountbandit'
  community.docker.docker_swarm_service:
    name: 'discountbandit'
    image: "cybrarist/discount-bandit:{{ discountbandit_release }}"
    force_update: true
    env:
      - 'APP_URL=https://discountbandit.rk1.mcharryville.space'
      - 'ASSET_URL=https://discountbandit.rk1.mcharryville.space'
      - 'DEFAULT_USER="test"'
      - 'DEFAULT_EMAIL="docker@test.com"'
      - 'DEFAULT_PASSWORD="thisismypassword"'
    mounts:
      - source: "{{ docker_data_dir }}/discountbandit-config/.env"
        target: '/app/.env'
        type: 'bind'
      # - source: "{{ docker_data_dir }}/discountbandit-data"
      #   target: '/logs/'
      #   type: 'bind'
      # - source: "{{ docker_data_dir }}/discountbandit-data/vendor"
      #   target: '/app/vendor'
      #   type: 'bind'
    networks:
      - 'discountbandit_backend'
      - 'traefik_backend'
    publish:
    labels:
      traefik.enable: "true"
      traefik.http.routers.discountbandit.rule: Host(`{{ discountbandit_app_name }}.{{ traefik_domain_rk1 }}`)
      traefik.http.routers.discountbandit.tls: "true"
      traefik.http.routers.discountbandit.entrypoints: websecure
      traefik.http.services.discountbandit.loadbalancer.server.port: "80"
    mode: 'replicated'
    # replicas: 2
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.role == worker'
  no_log: "{{ not docker_service_debug }}"