---
# tasks file for roles/apt-prep

# - name: Ensure apt cache is setup
#   ansible.builtin.copy:
#     src: 00aptproxy
#     dest: /etc/apt/apt.conf.d/00aptproxy

- name: Ensure apt cache is setup
  ansible.builtin.template:
    src: 00aptproxy.j2
    dest: /etc/apt/apt.conf.d/00aptproxy
    owner: root
    group: root
    mode: '0644'

- name: Update system
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  notify:
    - Schedule reboot if needed

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true
