---

## Title: ansible-rk1-cluster/roles/update/tasks/telegraf.yml
## Description: Install telegraf
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2026-03-19 11:02:05
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

## Refernece: https://docs.influxdata.com/telegraf/v1/install/

- name: Download GPG key for telegraf
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /tmp/influxdata-archive.gpg 

# Clean up influx stuff

- name: Remove apt influxdb repository configuration
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/influxdb.list
    state: absent

- name: Remove Broken key
  ansible.builtin.file:
    path: /etc/apt/keyrings/influxdata-archive.gpg
    state: absent

- name: Dearmor key and put in correct place
  ansible.builtin.command: "gpg --dearmor -o /etc/apt/keyrings/influxdata-archive.gpg /tmp/influxdata-archive.gpg"
  args:
    creates: /etc/apt/keyrings/influxdata-archive.gpg

- name: Copy influxdata repository configuration
  ansible.builtin.copy:
    src: influxdata.list
    dest: /etc/apt/sources.list.d/influxdata.list
    owner: root
    group: root
    mode: '0644'

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive.key
    state: present

- name: install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: latest
    update_cache: yes    