---
all:
  children:
    rk1_cluster:
      vars:
        install_nfs_server: true
      children:
        rk1_main:
          hosts:
            rk1-cluster02:
        rk1_secondary:
          hosts:
            rk1-cluster01:
            rk1-cluster02:
            rk1-cluster03:
            rk1-cluster04:

    
