---
all:
  children:
    rk1-cluster:
      children:
        rk1-main:
          hosts:
            rk1-cluster02:
        rk1_secondary:
          hosts:
            rk1-cluster01:
            rk1-cluster02:
            rk1-cluster03:
            rk1-cluster04:
    vars:
      install_nfs_server: true
    
