---
all:
  children:
    rk1-cluster:
      children:
        rk1-main:
          hosts:
            rk1-cluster02.mcharryville.space:
        rk1_secondary:
          hosts:
            rk1-cluster01.mcharryville.space:
            rk1-cluster02.mcharryville.space:
            rk1-cluster03.mcharryville.space:
            rk1-cluster04.mcharryville.space:
    vars:
      install_nfs_server: true
    
