http:
  routers:
    # containers
    ct-pihole:
      rule: "Host(`pihole01.mcharryville.space`)"
      tls: true
      entryPoints:
        - websecure
      service: ct-pihole
    ct-dns01:
      rule: "Host(`admin.dns01.mcharryville.space`)"
      tls: true
      entryPoints:
        - websecure
      service: ct-dns01
    # WLED Instances for Home Assistant Integration
    library-window:
      rule: "Host(`wled-librarywindow.wled.mcharryville.space`)"
      entryPoints:
        - websecure
      tls: true
      service: library-window
    garage-lights:
      rule: "Host(`wled-garage.wled.mcharryville.space`)"
      tls: true
      entryPoints:
        - websecure
      service: garage-lights


  services:
  # Containers
    ct-pihole:
      loadBalancer:
        servers:
          - url: "http://ct-pihole.mcharryville.space"
    ct-dns01:
      loadBalancer:
        servers:
          - url: "http://10.1.1.26:5380/"
    # WLED Instances
    library-window:
      loadBalancer:
        servers:
          - url: "http://wled-librarywindow.iot.mcharryville.space"
    garage-lights:
      loadBalancer:
        servers:
          - url: "http://wled-garage.iot.mcharryville.space"
    parents-lights:
      loadBalancer:
        servers:
          - url: "http://wled-parents.iot.mcharryville.space"

