---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: docker-grafana
      image: ubuntu
      image_version: latest
      ansible_groups:
        - group1
verifier:
  name: testinfra
