api:
  dashboard: true
  debug: true
  insecure: true

# metrics:
#   influxDB:
#     address: influx.mcharryville.space:8089
#     protocol: udp
#     database: traefik
#     retentionPolicy: "two_hours"
  # prometheus:
  #   entryPoint: metrics
# accesslog: true
sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dns-tcp:
    address: ":53"
  dns-udp:
    address: ":53/udp"
  aptcacher:
    address: ":3142"

tls:
  stores:
    default:
      defaultCertificate:
        certFile = "/certs/traefik.crt"
        keyFile = "/certs/traefik.key"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_backend
    swarmMode: true # This is for version 2
  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: findarato@gmail.com
      storage: acme.json
      certificatesDuration: 72
      caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"