[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/traefik.crt"
      keyFile = "/certs/traefik.key"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.dns-tcp]
    address = ":53"
  [entryPoints.dns-udp]
    address = ":53/udp"
