---
- name: Keepalived Install package
  ansible.builtin.apt:
    name: "keepalived"
    state: latest
    only_upgrade: true

- name: Keepalived Copy main config
  ansible.builtin.template:
    src: main.keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - cluster_role == "main"
  notify:
    - Restart_keepalived

- name: Keepalived Copy secondary config
  ansible.builtin.template:
    src: secondary.keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - cluster_role == "secondary"
  notify:
    - Restart_keepalived

- name: Keepalived Start and enable service
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
