---
# handlers file for roles/apt-prep

- name: Schedule reboot if needed
  ansible.builtin.reboot:
    msg: "Rebooting to apply updates"
    pre_reboot_delay: 10
    post_reboot_delay: 30
    test_command: uptime
  when: ansible_facts['pkg_mgr'] == 'apt'
